export * from './Home';
export * from './Shop';
export * from './Product';
export * from './PlacingOrder';
export * from './Contacts';
export * from './PaymentDelivery';
export * from './AboutUs';
export * from './Reviews';
export * from './Profile';
